root: true
extends:
  - plugin:prettier/recommended
  - plugin:github/recommended
env:
  node: true
  es2019: true
parserOptions:
  ecmaVersion: 9
rules:
  sort-imports: 0
  no-console: 0
  eslint-comments/no-use: 0
  eslint-comments/no-unlimited-disable: 0
